homepage:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Default:index }

hello:
    resource: HelloBundle/Resources/config/routing.yml

sqldemo:
    resource: SqlDemoBundle/Resources/config/routing.yml
